version: "2"
run:
  go: "1.24"
linters:
  enable:
    - dupl
    - goconst
    - gocritic
    - gocyclo
    - godot
    - goheader
    - goprintffuncname
    - gosec
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - unconvert
    - unparam
    - whitespace
  settings:
    dupl:
      threshold: 100
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
        - wrapperFunc
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
    gocyclo:
      min-complexity: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gocyclo
        path: _test\.go
      - linters:
          - dupl
          - goconst
          - gocyclo
        path: cmd/
      - linters:
          - gosec
        path: internal/helm/version_fetcher_test.go
        text: 'G404: Use of weak random number generator'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
