package main

// Hardcoded templates to avoid embed issues
var helmRepositoryTemplate = `apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{.HelmRepoName}}
  namespace: {{.Namespace}}
spec:
  interval: {{.Interval}}
  url: {{.HelmRepoURL}}
`

var helmReleaseTemplate = `apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{.AppName}}
  namespace: {{.Namespace}}
spec:
  interval: {{.Interval}}
  chart:
    spec:
      chart: {{.ChartName}}
      version: '{{.ChartVersion}}'
      sourceRef:
        kind: HelmRepository
        name: {{.HelmRepoName}}
      interval: {{.Interval}}
  valuesFrom:
    - kind: ConfigMap
      name: {{.AppName}}-values
      valuesKey: values.yaml
`

var helmValuesTemplate = `# Helm values for {{.AppName}}
# Generated by flux-app-generator

{{- range $key, $value := .Values }}
{{$key}}: {{$value}}
{{- end }}
`

var kustomizationTemplate = `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dependencies/helm-repository.yaml
  - release/helm-release.yaml

configMapGenerator:
  - name: {{.AppName}}-values
    files:
      - values.yaml=release/helm-values.yaml
    options:
      disableNameSuffixHash: true
` 