package generator

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/EffectiveSloth/flux-app-generator/internal/types"
)

func TestGenerateFromTemplateString(t *testing.T) {
	// Set up test templates
	HelmRepositoryTemplate = `apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: {{.HelmRepoName}}
  namespace: {{.Namespace}}
spec:
  interval: {{.Interval}}
  url: {{.HelmRepoURL}}`

	HelmReleaseTemplate = `apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{.AppName}}
  namespace: {{.Namespace}}
spec:
  interval: {{.Interval}}
  chart:
    spec:
      chart: {{.ChartName}}
      version: '{{.ChartVersion}}'
      sourceRef:
        kind: HelmRepository
        name: {{.HelmRepoName}}
      interval: {{.Interval}}
  valuesFrom:
    - kind: ConfigMap
      name: {{.AppName}}-values
      valuesKey: values.yaml`

	HelmValuesTemplate = `# Helm values for {{.AppName}}
# Generated by flux-app-generator

{{- range $key, $value := .Values }}
{{$key}}: {{$value}}
{{- end }}`

	KustomizationTemplate = `apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - dependencies/helm-repository.yaml
  - release/helm-release.yaml

configMapGenerator:
  - name: {{.AppName}}-values
    files:
      - values.yaml=release/helm-values.yaml
    options:
      disableNameSuffixHash: true`

	tests := []struct {
		name        string
		templateStr string
		data        interface{}
		expectError bool
	}{
		{
			name:        "valid template",
			templateStr: "Hello {{.Name}}!",
			data:        map[string]string{"Name": "World"},
			expectError: false,
		},
		{
			name:        "invalid template",
			templateStr: "Hello {{.Name}!", // Missing closing brace
			data:        map[string]string{"Name": "World"},
			expectError: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			tempDir := t.TempDir()
			outputPath := filepath.Join(tempDir, "test.txt")

			err := generateFromTemplateString(tt.templateStr, outputPath, tt.data)
			if tt.expectError && err == nil {
				t.Errorf("expected error but got none")
			}
			if !tt.expectError && err != nil {
				t.Errorf("unexpected error: %v", err)
			}

			if !tt.expectError {
				// Check if file was created
				if _, err := os.Stat(outputPath); os.IsNotExist(err) {
					t.Errorf("expected file to be created at %s", outputPath)
				}
			}
		})
	}
}

func TestGenerateHelmRepository(t *testing.T) {
	config := &types.AppConfig{
		HelmRepoName: "test-repo",
		Namespace:    "default",
		Interval:     "5m",
		HelmRepoURL:  "https://example.com/repo",
	}

	tempDir := t.TempDir()
	appDir := filepath.Join(tempDir, "test-app")
	if err := os.MkdirAll(appDir, 0755); err != nil {
		t.Fatalf("failed to create test directory: %v", err)
	}

	// Create the dependencies subdirectory
	depsDir := filepath.Join(appDir, "dependencies")
	if err := os.MkdirAll(depsDir, 0755); err != nil {
		t.Fatalf("failed to create dependencies directory: %v", err)
	}

	err := generateHelmRepository(config, appDir)
	if err != nil {
		t.Errorf("unexpected error: %v", err)
	}

	// Check if file was created
	expectedPath := filepath.Join(appDir, "dependencies", "helm-repository.yaml")
	if _, err := os.Stat(expectedPath); os.IsNotExist(err) {
		t.Errorf("expected file to be created at %s", expectedPath)
	}
}

func TestGenerateHelmRelease(t *testing.T) {
	config := &types.AppConfig{
		AppName:      "test-app",
		Namespace:    "default",
		HelmRepoName: "test-repo",
		ChartName:    "test-chart",
		ChartVersion: "1.0.0",
		Interval:     "5m",
	}

	tempDir := t.TempDir()
	appDir := filepath.Join(tempDir, "test-app")
	if err := os.MkdirAll(appDir, 0755); err != nil {
		t.Fatalf("failed to create test directory: %v", err)
	}

	// Create the release subdirectory
	releaseDir := filepath.Join(appDir, "release")
	if err := os.MkdirAll(releaseDir, 0755); err != nil {
		t.Fatalf("failed to create release directory: %v", err)
	}

	err := generateHelmRelease(config, appDir)
	if err != nil {
		t.Errorf("unexpected error: %v", err)
	}

	// Check if file was created
	expectedPath := filepath.Join(appDir, "release", "helm-release.yaml")
	if _, err := os.Stat(expectedPath); os.IsNotExist(err) {
		t.Errorf("expected file to be created at %s", expectedPath)
	}
}

func TestGenerateHelmValues(t *testing.T) {
	config := &types.AppConfig{
		AppName: "test-app",
		Values: map[string]interface{}{
			"replicaCount": 3,
			"image": map[string]string{
				"repository": "nginx",
				"tag":        "latest",
			},
		},
	}

	tempDir := t.TempDir()
	appDir := filepath.Join(tempDir, "test-app")
	if err := os.MkdirAll(appDir, 0755); err != nil {
		t.Fatalf("failed to create test directory: %v", err)
	}

	// Create the release subdirectory
	releaseDir := filepath.Join(appDir, "release")
	if err := os.MkdirAll(releaseDir, 0755); err != nil {
		t.Fatalf("failed to create release directory: %v", err)
	}

	err := generateHelmValues(config, appDir)
	if err != nil {
		t.Errorf("unexpected error: %v", err)
	}

	// Check if file was created
	expectedPath := filepath.Join(appDir, "release", "helm-values.yaml")
	if _, err := os.Stat(expectedPath); os.IsNotExist(err) {
		t.Errorf("expected file to be created at %s", expectedPath)
	}
}

func TestGenerateKustomization(t *testing.T) {
	config := &types.AppConfig{
		AppName: "test-app",
	}

	tempDir := t.TempDir()
	appDir := filepath.Join(tempDir, "test-app")
	if err := os.MkdirAll(appDir, 0755); err != nil {
		t.Fatalf("failed to create test directory: %v", err)
	}

	err := generateKustomization(config, appDir)
	if err != nil {
		t.Errorf("unexpected error: %v", err)
	}

	// Check if file was created
	expectedPath := filepath.Join(appDir, "kustomization.yaml")
	if _, err := os.Stat(expectedPath); os.IsNotExist(err) {
		t.Errorf("expected file to be created at %s", expectedPath)
	}
}

func TestGenerateFluxStructure(t *testing.T) {
	config := &types.AppConfig{
		AppName:      "test-app",
		Namespace:    "default",
		HelmRepoName: "test-repo",
		HelmRepoURL:  "https://example.com/repo",
		ChartName:    "test-chart",
		ChartVersion: "1.0.0",
		Interval:     "5m",
		Values: map[string]interface{}{
			"replicaCount": 3,
		},
	}

	tempDir := t.TempDir()
	originalWd, err := os.Getwd()
	if err != nil {
		t.Fatalf("failed to get current working directory: %v", err)
	}

	// Change to temp directory for test
	if err := os.Chdir(tempDir); err != nil {
		t.Fatalf("failed to change to temp directory: %v", err)
	}
	defer func() {
		if err := os.Chdir(originalWd); err != nil {
			t.Errorf("failed to restore working directory: %v", err)
		}
	}()

	err = GenerateFluxStructure(config)
	if err != nil {
		t.Errorf("unexpected error: %v", err)
	}

	// Check if all expected files were created
	expectedFiles := []string{
		"test-app/dependencies/helm-repository.yaml",
		"test-app/release/helm-release.yaml",
		"test-app/release/helm-values.yaml",
		"test-app/kustomization.yaml",
	}

	for _, file := range expectedFiles {
		if _, err := os.Stat(file); os.IsNotExist(err) {
			t.Errorf("expected file to be created: %s", file)
		}
	}
}

func TestGenerateFluxStructure_DirectoryCreationError(t *testing.T) {
	config := &types.AppConfig{
		AppName: "", // Empty name should cause directory creation to fail
	}

	err := GenerateFluxStructure(config)
	if err == nil {
		t.Errorf("expected error for empty app name")
	}
}
